### ISSUE TITLE
能否增加对于Stream的upstream的适配？

### ISSUE THREAD

**Issue by ConstasJ** [zhaofeng0019/nginx-upstream-dynamic-resolve-servers#10]
按照http那边的模式试着编译了一下，但结构体名称啥的Stream那边和http不太一样，可能需要给一个官方指南？
我这边编译通过了也会在这边记录一下我的编译过程

**Comment by zhaofeng0019** [comment]
sorry to say that I'm not interested in this project furthermore nginx anymore, so maybe you can find another project or solve your problem by yourself.
