### ISSUE TITLE
能否增加对upstream keepalive的支持？

### ISSUE THREAD

**Issue by wohaiaini** [zhaofeng0019/nginx-upstream-dynamic-resolve-servers#11]
能否增加一下对 upstream keepalive 的支持，还是说已经支持了，是我没用好？谢谢
/* TODO: NGX_PEER_KEEPALIVE */

**Comment by wohaiaini** [comment]
@zhaofeng0019

**Comment by zhaofeng0019** [comment]
sorry to say that I'm not interested in this project furthermore nginx anymore, so maybe you can find another project or solve your problem by yourself.
