### ISSUE TITLE
Crashing when multiple upstream server has resolve param

### ISSUE THREAD

**Issue by JakubOnderka** [zhaofeng0019/nginx-upstream-dynamic-resolve-servers#9]
Imagine this simple configuration:

```
upstream upstream {
    server example.org resolve;
    server example.com resolve;
    server example.org resolve;
}
```

When just first upstream contains resolve param, everything works fine. But when multiple upstream servers has resolve param, nginx worker process fail with error in log like this:

```
socket() failed (97: Address family not supported by protocol) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "https://J?./", host: "localhost"
```

followed by worker crash. I will try to debug

**Comment by zhaofeng0019** [comment]
sorry to say that I'm not interested in this project furthermore nginx anymore, so maybe you can find another project or solve your problem by yourself.
